version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: myLock
      POSTGRES_USER: sirajudheen
      POSTGRES_DB: qdeals

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
