# Generated by Django 2.0 on 2018-06-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('address', models.CharField(max_length=700)),
            ],
        ),
        migrations.RemoveField(
            model_name='deal',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='location_long',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='vendor_address',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='vendor_contact',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.Vendor'),
        ),
        migrations.AddField(
            model_name='deal',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.Vendor'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.Vendor'),
        ),
    ]
