# Generated by Django 2.0.5 on 2018-06-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quser',
            name='provider',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
