# Generated by Django 2.0 on 2018-06-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_quser_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quser',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
