# Generated by Django 2.0 on 2018-06-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180621_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='quser',
            name='profile_picture',
            field=models.URLField(null=True),
        ),
    ]
